// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RydePlannr.Infrastructure.Persistence;

#nullable disable

namespace RydePlannr.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504165210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RydePlannr.Domain.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("integer");

                    b.Property<int>("RideTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("RideTypeId");

                    b.HasIndex("RouteId");

                    b.ToTable("RideEvents", (string)null);
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RideEventId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RideEventId");

                    b.HasIndex("UserId");

                    b.ToTable("RideParticipants");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RideTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Opuštena vožnja bez vremenskog pritiska",
                            Name = "Leisure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Strukturirana vožnja s ciljem poboljšanja forme",
                            Name = "Training"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kompetitivna vožnja s mjerenjem vremena",
                            Name = "Race"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Masovna sportska vožnja na duge relacije",
                            Name = "Gran Fondo"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Noćna vožnja",
                            Name = "Night Ride"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vožnja organizirana u dobrotvorne svrhe s prikupljanjem donacija",
                            Name = "Charity Ride"
                        });
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("ElevationGain")
                        .HasColumnType("integer");

                    b.Property<int>("EndLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StartLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EndLocationId");

                    b.HasIndex("StartLocationId");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Club", b =>
                {
                    b.HasOne("RydePlannr.Domain.Entities.User", "Owner")
                        .WithOne("OwnedClub")
                        .HasForeignKey("RydePlannr.Domain.Entities.Club", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideEvent", b =>
                {
                    b.HasOne("RydePlannr.Domain.Entities.Club", "Club")
                        .WithMany("RideEvents")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RydePlannr.Domain.Entities.User", "Organizer")
                        .WithMany("OrganizedRides")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RydePlannr.Domain.Entities.RideType", "RideType")
                        .WithMany("RideEvents")
                        .HasForeignKey("RideTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RydePlannr.Domain.Entities.Route", "Route")
                        .WithMany("RideEvents")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Organizer");

                    b.Navigation("RideType");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideParticipant", b =>
                {
                    b.HasOne("RydePlannr.Domain.Entities.RideEvent", "RideEvent")
                        .WithMany("Participants")
                        .HasForeignKey("RideEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RydePlannr.Domain.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RideEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Route", b =>
                {
                    b.HasOne("RydePlannr.Domain.Entities.Location", "EndLocation")
                        .WithMany("RoutesAsEnd")
                        .HasForeignKey("EndLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RydePlannr.Domain.Entities.Location", "StartLocation")
                        .WithMany("RoutesAsStart")
                        .HasForeignKey("StartLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EndLocation");

                    b.Navigation("StartLocation");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.User", b =>
                {
                    b.HasOne("RydePlannr.Domain.Entities.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RydePlannr.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Club", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RideEvents");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Location", b =>
                {
                    b.Navigation("RoutesAsEnd");

                    b.Navigation("RoutesAsStart");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideEvent", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.RideType", b =>
                {
                    b.Navigation("RideEvents");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.Route", b =>
                {
                    b.Navigation("RideEvents");
                });

            modelBuilder.Entity("RydePlannr.Domain.Entities.User", b =>
                {
                    b.Navigation("OrganizedRides");

                    b.Navigation("OwnedClub");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
